FROM node:16-alpine
LABEL author="CYDEVATECH <info@cydva.com>"

WORKDIR /app

RUN apk add --no-cache git \
    && npm install --frozen-lockfile \

COPY . .
RUN npm build

EXPOSE 3000

CMD ["npm", "start"]